wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1645712357
    t:
      3:
      - 2
      4: 3.9.7
      5: 0.12.10
      8:
      - 1
      - 5
drop:
  desc: null
  value: 4
lr:
  desc: null
  value: 5
