wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1644324629
    t:
      1:
      - 1
      3:
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 1
dropout:
  desc: null
  value: 0.5000000000000001
epochs:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.01
