wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: ignite
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1646220696
    t:
      1:
      - 1
      - 10
      2:
      - 1
      - 10
      3:
      - 2
      4: 3.9.7
      5: 0.12.10
      8:
      - 1
      - 5
